### PR TITLE
AGC modes added

### PR DESCRIPTION
**Pull request by litscham**
I added commands to get and set AGC mode for Boson

### CODE REVIEW

**Comment by jveitchmichaelis** [comment]
Thanks! Would it be possible to add tests that check if the mode is set correctly?

**Comment by jveitchmichaelis** [comment]
@litscham I added some review notes - unfortunately I don't have a Boson to test with at the moment so if you could implement the tests on your end and check they run, that'd be great and I'll merge it.

**Comment by litscham** [comment]
I'll check it out once I have the time

**Comment by litscham** [comment]
I tested on different firmware revs and the option to set and get AGC only worked on the newest 3.0.25868 firmware

**Comment by jveitchmichaelis** [comment]
Great. I guess we could add a check for the firmware revision (e.g. via `get_firmware_revision`), but I think we can add it as-is.

**Pull request closed without merging**
